version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassw0rd2
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    # volumes:
    #   - mssql-data:/var/opt/mssql/data
    networks:
      - app-network

# volumes:
#   mssql-data:

networks:
  app-network:
    driver: bridge